name       : python-openssl
version    : 19.0.0
release    : 11
source     :
    - https://github.com/pyca/pyopenssl/archive/19.0.0.tar.gz : c5689bb12c210e3f996ee0a49cee8867f2afbf7e9beb84f3522f9dc8fdcb83ae
license    : Apache-2.0
component  : programming.python
summary    : Python interface to the OpenSSL library
description: |
    pyOpenSSL - A Python wrapper around the OpenSSL library
builddeps  :
    - pkgconfig(python3)
    - python-cryptography
    - python-flaky
    - python-pretend
    - python-pytest
    - python-setuptools
rundeps    :
    - python-cryptography
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test py.test -v -k 'not test_set_default_verify_paths'
#    %python3_test py.test3 -v -k 'not test_set_default_verify_paths'
