name       : python-openssl
version    : 16.2.0
release    : 2
source     :
    - https://pypi.python.org/packages/0c/d6/b1fe519846a21614fa4f8233361574eddb223e0bc36b182140d916acfb3b/pyOpenSSL-16.2.0.tar.gz : 7779a3bbb74e79db234af6a08775568c6769b5821faecf6e2f4143edb227516e
homepage   : https://github.com/pyca/pyopenssl
license    : GPL-2.0
component  : programming.python
summary    : Python interface to the OpenSSL library
description: |
    pyOpenSSL - A Python wrapper around the OpenSSL library
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
