name       : python-openssl
version    : 19.1.0
release    : 13
source     :
    - https://github.com/pyca/pyopenssl/archive/refs/tags/19.1.0.tar.gz : 7142f50ed9f97c079f6e63c082f3d1919cc52ddb0c03d5f6d77b55e18e8cdeff
license    : Apache-2.0
component  : programming.python
summary    : Python interface to the OpenSSL library
description: |
    pyOpenSSL - A Python wrapper around the OpenSSL library
builddeps  :
    - pkgconfig(python3)
    - python-cryptography
    - python-flaky
    - python-pretend
    - python-pytest
rundeps    :
    - python-cryptography
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # Re-enable on 20.0.0/OpenSSL 1.1.0
    %python3_test py.test3 -v -k 'not (test_set_default_verify_paths or test_add_extra_chain_cert or test_use_certificate_chain_file_bytes or test_use_certificate_chain_file_unicode)'
