name       : python-openssl
version    : 17.0.0
release    : 3
source     :
    - https://pypi.python.org/packages/9f/32/80fe4fddeb731b7766cd09fe0b2032a91b43dae655e216792af2a6ae3190/pyOpenSSL-17.0.0.tar.gz : 48abfe9d2bb8eb8d8947c8452b0223b7b1be2383b332f3b4f248fe59ef0bafdd
license    : GPL-2.0
component  : programming.python
summary    : Python interface to the OpenSSL library
description: |
    pyOpenSSL - A Python wrapper around the OpenSSL library
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
