name       : python-openssl
version    : 18.0.0
release    : 8
source     :
    - https://github.com/pyca/pyopenssl/archive/18.0.0.tar.gz : 4cbd406aac16077ed23c77e35c38852cd4825a5fcf06beebd243349882da25e6
license    : Apache-2.0
component  : programming.python
summary    : Python interface to the OpenSSL library
description: |
    pyOpenSSL - A Python wrapper around the OpenSSL library
builddeps  :
    - pkgconfig(python3)
    - python-cryptography
    - python-flaky
    - python-pretend
    - python-pytest
    - python-setuptools
rundeps    :
    - python-cryptography
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    # there are still failing tests that we must fix
    pushd $PKG_BUILD_DIR/py2build
        # PYTHONPATH=$installdir/usr/lib/python2.7/site-packages py.test
    popd

    pushd $PKG_BUILD_DIR/py3build
        # PYTHONPATH=$installdir/usr/lib/python3.5/site-packages py.test3
    popd
