name       : python-openssl
version    : 17.5.0
release    : 7
source     :
    - https://pypi.io/packages/source/p/pyOpenSSL/pyOpenSSL-17.5.0.tar.gz : 2c10cfba46a52c0b0950118981d61e72c1e5b1aac451ca1bc77de1a679456773
license    : GPL-2.0
component  : programming.python
summary    : Python interface to the OpenSSL library
description: |
    pyOpenSSL - A Python wrapper around the OpenSSL library
builddeps  :
    - pkgconfig(python3)
    - python-cryptography
    - python-flaky
    - python-pretend
    - python-pytest
    - python-setuptools
rundeps    :
    - python-cryptography
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    # there are still failing tests that we must fix
    pushd $PKG_BUILD_DIR/py2build
        # PYTHONPATH=$installdir/usr/lib/python2.7/site-packages py.test
    popd

    pushd $PKG_BUILD_DIR/py3build
        # PYTHONPATH=$installdir/usr/lib/python3.5/site-packages py.test3
    popd
