name       : python-openssl
version    : 23.2.0
release    : 14
source     :
    - https://github.com/pyca/pyopenssl/archive/refs/tags/23.2.0.tar.gz : a5af3dd778be50880a122b9ff480d1c302543b60c420c7dabc8bf77de976ffc6
homepage   : https://pyopenssl.org/
license    : Apache-2.0
component  : programming.python
summary    : Python interface to the OpenSSL library
description: |
    pyOpenSSL - A Python wrapper around the OpenSSL library
builddeps  :
    - pkgconfig(python3)
    - python-cryptography
    - python-flaky
    - python-pretend
    - python-pytest
rundeps    :
    - python-cryptography
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # Re-enable on 20.0.0/OpenSSL 1.1.0
    %python3_test py.test -v -k 'not (test_set_default_verify_paths or test_add_extra_chain_cert or test_use_certificate_chain_file_bytes or test_use_certificate_chain_file_unicode)'
